name: 'Very DogeOps'
author: 'Carlos Gonzalez'
description: 'Checks that this project is DogeOps enabled'

inputs:
  config_file:  # id of input
    description: 'Path to the config file'
    required: false
    default: '.dogeops.yml'

outputs:
  dogeops:
    description: "Whether this project is DogeOps enabled"
  tf_backend:
    description: "When defined, the path to the Terraform backend config file"

runs:
  using: 'node16'
  main: 'dist/index.js'
